import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:intl/intl.dart';
import 'package:shimmer/shimmer.dart';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class DiaryScreen extends StatefulWidget {
  const DiaryScreen({super.key});
  @override
  State<DiaryScreen> createState() => _DiaryScreenState();
}

class _DiaryScreenState extends State<DiaryScreen> {
  List<Map<String, dynamic>> _profiles = [];
  List<Map<String, dynamic>> _allLogs = [];

  String? _viewingProfileId;
  bool _isLoading = true;
  String _system = 'metric';

  @override
  void initState() {
    super.initState();
    _loadDiary();
  }

  Future<void> _loadDiary() async {
    await Future.delayed(const Duration(milliseconds: 600));

    final prefs = await SharedPreferences.getInstance();
    _system = prefs.getString('setting_system') ?? 'metric';

    List<String> savedProfiles = prefs.getStringList('ibhwc_profiles') ?? [];
    List<String> savedData = prefs.getStringList('ibhwc_diary') ?? [];

    _profiles = savedProfiles.map((e) => jsonDecode(e) as Map<String, dynamic>).toList();

    _allLogs = savedData.map((e) {
      final map = jsonDecode(e) as Map<String, dynamic>;
      map['id'] ??= DateTime.now().microsecondsSinceEpoch.toString();
      return map;
    }).toList().reversed.toList();

    setState(() {
      _isLoading = false;
    });
  }

  int _getLogCount(String profileId) {
    return _allLogs.where((log) => log['profileId'] == profileId).length;
  }

  Future<void> _deleteLog(String logId) async {
    final prefs = await SharedPreferences.getInstance();
    setState(() {
      _allLogs.removeWhere((log) => log['id'] == logId);
    });
    await prefs.setStringList('ibhwc_diary', _allLogs.reversed.map((e) => jsonEncode(e)).toList());
    if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Record deleted.'), behavior: SnackBarBehavior.floating));
  }

  String _formatLogWeight(double kgVal) { return _system == 'imperial' ? '${(kgVal * 2.20462).toStringAsFixed(1)} lbs' : '${kgVal.toStringAsFixed(1)} kg'; }
  String _formatLogHeight(double cmVal) { return _system == 'imperial' ? '${(cmVal / 2.54).toStringAsFixed(1)} in' : '${cmVal.toStringAsFixed(1)} cm'; }

  Future<void> _exportProfileDiaryPdf(String profileId) async {
    final childLogs = _allLogs.where((log) => log['profileId'] == profileId).toList();
    if (childLogs.isEmpty) return;

    final pdf = pw.Document();
    final profile = _profiles.firstWhere((p) => p['id'] == profileId);

    final List<List<String>> tableData = childLogs.map((log) {
      final date = DateFormat('MMM d, yyyy').format(DateTime.parse(log['date']));
      double wKg = (log['weight'] as num).toDouble();
      double hCm = (log['height'] as num).toDouble();
      return <String>[date, '${log['age'].toStringAsFixed(1)} yrs', _formatLogWeight(wKg), _formatLogHeight(hCm)];
    }).toList();

    pdf.addPage(
        pw.MultiPage(
            pageFormat: PdfPageFormat.a4,
            margin: const pw.EdgeInsets.all(32),
            build: (pw.Context context) {
              return [
                pw.Header(level: 0, child: pw.Text('${profile['name']}\'s Growth Diary', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.teal))),
                pw.SizedBox(height: 10),
                pw.Text('Exported on: ${DateFormat('MMMM d, yyyy').format(DateTime.now())}', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                pw.SizedBox(height: 20),
                pw.TableHelper.fromTextArray(
                  context: context, headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200), headerHeight: 40, cellHeight: 35,
                  cellAlignments: {0: pw.Alignment.centerLeft, 1: pw.Alignment.center, 2: pw.Alignment.centerRight, 3: pw.Alignment.centerRight},
                  headers: ['Date Recorded', 'Age', 'Weight', 'Height'], data: tableData,
                ),
                pw.SizedBox(height: 30),
                pw.Center(child: pw.Text('Generated by Indian Baby Height Weight Calculator - Based on WHO & IAP Standards', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500))),
              ];
            }
        )
    );
    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save(), name: '${profile['name']}_Diary.pdf');
  }

  Widget _buildShimmerLoading() {
    return GridView.builder(
      padding: const EdgeInsets.all(16),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2, crossAxisSpacing: 16, mainAxisSpacing: 16, childAspectRatio: 0.85),
      itemCount: 4,
      itemBuilder: (context, index) {
        return Shimmer.fromColors(
          baseColor: Colors.grey.shade300,
          highlightColor: Colors.grey.shade100,
          child: Container(
            decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(24)),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return Scaffold(
        backgroundColor: Theme.of(context).colorScheme.surface,
        appBar: AppBar(title: const Text('My Growth Diaries', style: TextStyle(fontWeight: FontWeight.bold)), backgroundColor: Colors.transparent, elevation: 0),
        body: _buildShimmerLoading(),
      );
    }

    if (_viewingProfileId == null) {
      return Scaffold(
        backgroundColor: Theme.of(context).colorScheme.surface,
        appBar: AppBar(title: const Text('My Growth Diaries', style: TextStyle(fontWeight: FontWeight.bold)), backgroundColor: Colors.transparent, elevation: 0),
        body: _profiles.isEmpty
            ? Center(
            child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
              Container(
                padding: const EdgeInsets.all(32),
                decoration: BoxDecoration(color: Theme.of(context).colorScheme.primaryContainer, shape: BoxShape.circle),
                child: Icon(Icons.family_restroom, size: 80, color: Theme.of(context).colorScheme.primary),
              ),
              const SizedBox(height: 24),
              const Text('No Profiles Yet!', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.black87)),
              const SizedBox(height: 12),
              Text('Head over to the Home Screen to add\nyour child and start tracking their growth.', textAlign: TextAlign.center, style: TextStyle(color: Colors.grey.shade600, fontSize: 16, height: 1.4))
            ])
        )
            : GridView.builder(
          padding: const EdgeInsets.all(16),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2, crossAxisSpacing: 16, mainAxisSpacing: 16, childAspectRatio: 0.85),
          itemCount: _profiles.length,
          itemBuilder: (context, index) {
            final p = _profiles[index];
            int count = _getLogCount(p['id']);
            MaterialColor color = p['gender'] == 'boys' ? Colors.blue : Colors.pink;

            return InkWell(
              onTap: () => setState(() => _viewingProfileId = p['id']),
              borderRadius: BorderRadius.circular(24),
              child: Container(
                decoration: BoxDecoration(
                  gradient: LinearGradient(colors: [color.shade400, color.shade300], begin: Alignment.topLeft, end: Alignment.bottomRight),
                  borderRadius: BorderRadius.circular(24),
                  boxShadow: [BoxShadow(color: color.withOpacity(0.3), blurRadius: 10, offset: const Offset(0, 5))],
                ),
                child: Padding(
                  padding: const EdgeInsets.all(20.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(color: Colors.white.withOpacity(0.2), shape: BoxShape.circle),
                        child: Icon(p['gender'] == 'boys' ? Icons.boy : Icons.girl, size: 36, color: Colors.white),
                      ),
                      const Spacer(),
                      Text(p['name'], style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: Colors.white), maxLines: 1, overflow: TextOverflow.ellipsis),
                      const SizedBox(height: 4),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                        decoration: BoxDecoration(color: Colors.white.withOpacity(0.2), borderRadius: BorderRadius.circular(12)),
                        child: Text('$count records', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w600, fontSize: 12)),
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      );
    }

    final activeProfile = _profiles.firstWhere((p) => p['id'] == _viewingProfileId);
    final childLogs = _allLogs.where((log) => log['profileId'] == _viewingProfileId).toList();
    Color themeColor = activeProfile['gender'] == 'boys' ? Colors.blue : Colors.pink;

    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.surface,
      appBar: AppBar(
          leading: IconButton(icon: const Icon(Icons.arrow_back), onPressed: () => setState(() => _viewingProfileId = null)),
          title: Text('${activeProfile['name']}\'s Timeline', style: const TextStyle(fontWeight: FontWeight.bold)),
          backgroundColor: Colors.transparent,
          elevation: 0
      ),
      body: childLogs.isEmpty
          ? Center(
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
            Container(
              padding: const EdgeInsets.all(32),
              decoration: BoxDecoration(color: themeColor.withOpacity(0.1), shape: BoxShape.circle),
              child: Icon(Icons.straighten, size: 80, color: themeColor),
            ),
            const SizedBox(height: 24),
            const Text('No Logs Found', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.black87)),
            const SizedBox(height: 12),
            Text('Check their height and weight on the\nHome Screen and tap "Save" to build the timeline!', textAlign: TextAlign.center, style: TextStyle(color: Colors.grey.shade600, fontSize: 16, height: 1.4))
          ])
      )
          : ListView.builder(
        padding: const EdgeInsets.only(left: 16, right: 16, top: 16, bottom: 100),
        itemCount: childLogs.length,
        itemBuilder: (context, index) {
          final log = childLogs[index];
          final DateTime date = DateTime.parse(log['date']);
          final String month = DateFormat('MMM').format(date);
          final String day = DateFormat('dd').format(date);

          double wKg = (log['weight'] as num).toDouble();
          double hCm = (log['height'] as num).toDouble();

          return Dismissible(
            key: Key(log['id']),
            direction: DismissDirection.endToStart,
            background: Container(alignment: Alignment.centerRight, padding: const EdgeInsets.only(right: 20.0), decoration: BoxDecoration(color: Colors.red.shade400, borderRadius: BorderRadius.circular(16)), child: const Icon(Icons.delete, color: Colors.white, size: 30)),
            onDismissed: (direction) => _deleteLog(log['id']),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Column(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(color: themeColor.withOpacity(0.1), borderRadius: BorderRadius.circular(12)),
                      child: Column(
                        children: [
                          Text(month.toUpperCase(), style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: themeColor)),
                          Text(day, style: TextStyle(fontSize: 18, fontWeight: FontWeight.w900, color: themeColor)),
                        ],
                      ),
                    ),
                    if (index != childLogs.length - 1)
                      Container(width: 2, height: 60, color: themeColor.withOpacity(0.2), margin: const EdgeInsets.only(top: 8)),
                  ],
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Card(
                    elevation: 0,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16), side: BorderSide(color: Colors.grey.shade200)),
                    margin: const EdgeInsets.only(bottom: 24),
                    child: Padding(
                      padding: const EdgeInsets.all(16.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text('Age: ${log['age'].toStringAsFixed(1)} years', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                              Icon(Icons.swipe_left, size: 16, color: Colors.grey.shade300),
                            ],
                          ),
                          const SizedBox(height: 12),
                          Row(
                            children: [
                              _buildMetricChip(Icons.monitor_weight_outlined, _formatLogWeight(wKg), themeColor),
                              const SizedBox(width: 12),
                              _buildMetricChip(Icons.height, _formatLogHeight(hCm), themeColor),
                            ],
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      floatingActionButton: childLogs.isNotEmpty
          ? FloatingActionButton.extended(onPressed: () => _exportProfileDiaryPdf(_viewingProfileId!), icon: const Icon(Icons.picture_as_pdf), label: const Text('Export Timeline to PDF', style: TextStyle(fontWeight: FontWeight.bold)), backgroundColor: Colors.redAccent, foregroundColor: Colors.white)
          : null,
    );
  }

  Widget _buildMetricChip(IconData icon, String value, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: BoxDecoration(color: Colors.grey.shade100, borderRadius: BorderRadius.circular(8)),
      child: Row(
        children: [
          Icon(icon, size: 16, color: color),
          const SizedBox(width: 6),
          Text(value, style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 13, color: Colors.black87)),
        ],
      ),
    );
  }
}